name: CI

on: [push, pull_request]

jobs:
  build:
    name: Generate build and check code formatting

    runs-on: ubuntu-latest

    steps:
      - name: Profile ReadMe - GitHub Activity
        uses: 4lch4/github-activity-readme@v0.3.7
